export const OfficeAssets = {
  textureKey: 'office-assets',
  backgroundKey: 'office-background',
  metadataKey: 'office-assets-metadata',
  spritesheetPath: 'assets/office/office_assets_spritesheet.png',
  backgroundPath: 'assets/office/office_bakcground.png',
  atlasPath: 'assets/office/office_assets_atlas.json',
  metadataPath: 'assets/office/office_assets_atlas_cleaned.json',
  ceoTableIntactKey: 'ceo-table-intact',
  ceoTableBrokenKey: 'ceo-table-broken',
  ceoTableIntactPath: 'assets/office/ceo_table_intact.png',
  ceoTableBrokenPath: 'assets/office/ceo_table_broken.png',
  bossKey: 'boss-image',
  bossPath: 'assets/boss.png',
} as const;

export const OfficeAssetFrames = {
  doorMat01: 'door_mat_01',
  tallPottedPlant: 'tall_potted_plant',
  coffeeStationTable: 'coffee_station_table',
  cardboardStackLarge: 'cardboard_stack_large',
  smallPottedCactus: 'small_potted_cactus',
  largePottedPlant: 'large_potted_plant',
  paperShredder: 'paper_shredder',
  waterCooler: 'water_cooler',
  waterCoolerBroken: 'water_cooler_broken',
  doorMat02: 'door_mat_02',
  lowCabinetWithPlant: 'low_cabinet_with_plant',
  fileCabinetSingle01: 'file_cabinet_single_01',
  fileCabinetSingle02: 'file_cabinet_single_02',
  fileCabinetSingle03: 'file_cabinet_single_03',
  cardboardStackSmall: 'cardboard_stack_small',
  blueStorageUnit: 'blue_storage_unit',
  trashCan: 'trash_can',
  trashCanBroken: 'trash_can_broken',
  bookcaseNormal: 'bookcase_normal',
  bookcaseBroken: 'bookcase_broken',
  storageCabinetNormal: 'storage_cabinet_normal',
  storageCabinetBroken: 'storage_cabinet_broken',
  doubleDesksNormal: 'double_desks_normal',
  doubleDesksBroken: 'double_desks_broken',
  singleDeskNormal: 'single_desk_normal',
  singleDeskBroken: 'single_desk_broken',
  copierNormal: 'copier_normal',
  copierBroken: 'copier_broken',
  filingCabinetsNormal: 'filing_cabinets_normal',
  filingCabinetsBroken: 'filing_cabinets_broken',
} as const;

export type OfficeAssetFrame = (typeof OfficeAssetFrames)[keyof typeof OfficeAssetFrames];
